site_name: ProtoGame
repo_url: 'https://github.com/Design-de-Jogos/2020.1-Prototyping'
theme:
  name: 'material'
nav:
  - Home: index.md
  - Sobre o projeto:
    - Equipe: equipe.md
    - Cronograma: Cronograma.md
    - Ferramentas: ferramentas.md
  - Análise de Requisitos:
    - Visão do Produto: Visao.md
    - Perfil do Usuário: Perfil-usuario.md
    - Personas: Persona.md
    - Descrição do Jogo: Descricao-jogo.md
    - Recursos do Produto: recursos-produto.md
    - Storyboards: storyboard.md
    - Análise de Tarefas: analise_de_tarefas.md
    - Princípios e Diretrizes para o Design: diretrizesDesign.md
    - Guia de Estilo: Usabilidade.md
  - Design, Avaliação:
    - Planejamento das Avaliações: 
      - Storyboard: Planejamento-Avaliacao.md
      - Protótipo de Papel : Planejamento-avaliacao-prototipo-papel.md
      - Prototipo de Alta Fidelidade: Planejamento-prototipo-alta-fidelidade.md
    - Análise dos Resultados da Avaliação: 
      - Storyboards: Avaliacao-storyboard.md
      - Protótipo de Papel: analise-prototipo.md
      - Protótipo de Alta Fidelidade: Avaliacao-relato-resultados-proto-alta-fidelidade
  - Gerenciamento:
    - Riscos: Riscos.md
    - Reuniões: Reuniao.md 
  - Verificação:
    - Planejamento: PlanVerificacao.md
  - Apresentações:
    - Apresentações: Apresentacao.md
