site_name: Prototyping
repo_url: 'https://github.com/Design-de-Jogos/2020.1-Prototyping'

pages:
 - Sobre o projeto:
   - Home: index.md
 - Análise de Requisitos :clipboard::
   - Visão do produto: Visao.md
