site_name: ProtoGame
repo_url: 'https://github.com/Design-de-Jogos/2020.1-Prototyping'
theme:
  name: 'material'
nav:
 - Home: index.md
 - Sobre o projeto:
   - Cronograma: Cronograma.md
 - Análise de Requisitos:
   - Visão do produto: Visao.md
   - Perfil do Usuário: Perfil-usuario.md
   - Persona: Persona.md
   - Descrição do Jogo: Descricao-jogo.md
   - Recursos do produto: recursos-produto.md
   - Storyboard: storyboard.md
   - Análise de Tarefas: analise_de_tarefas.md
   - Princípios e Diretrizes para o Design: diretrizesDesign.md
   - Guia de Estilo: Usabilidade.md
   - Ferramentas: ferramentas.md
 - Design, Avaliação:
   - Planejamento das Avaliações: Planejamento-Avaliacao.md
   - Análise dos Resultados da Avaliação dos Storyboards: Avaliacao-storyboard.md
 - Gerenciamento:
   - Riscos: Riscos.md
   - Reuniões: Reuniao.md
 - Apresentações:
   - Apresentações: Apresentacao.md
