site_name: Prototyping
repo_url: 'https://github.com/Design-de-Jogos/2020.1-Prototyping'
theme:
  name: 'material'
nav:
 - Sobre o projeto:
   - Home: index.md
 - Análise de Requisitos:
   - Visão do produto: Visao.md
   - Perfil do Usuário: Perfil-usuario.md
   - Persona: Persona.md
   - Descrição do Jogo: Descricao-jogo.md
   - Análise de Tarefas: analise_de_tarefas.md
   - Storyboard: storyboard.md 
   - Guia de Estilo: Usabilidade.md
 - Gerenciamento:
   - Gerenciamento de tempo: Cronograma.md
   - Riscos: Riscos.md
   - Reuniões: Reuniao.md
 - Apresentações:
   - Apresentações: Apresentacao.md
